//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:17:16 PM CET 
//


package org.sphpp.nextprot.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for evidenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="evidenceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="POTENTIAL"/>
 *     &lt;enumeration value="PROBABLE"/>
 *     &lt;enumeration value="BY_SIMILARITY"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="EXP"/>
 *     &lt;enumeration value="IDA"/>
 *     &lt;enumeration value="IPI"/>
 *     &lt;enumeration value="IMP"/>
 *     &lt;enumeration value="IGI"/>
 *     &lt;enumeration value="IEP"/>
 *     &lt;enumeration value="ISS"/>
 *     &lt;enumeration value="ISO"/>
 *     &lt;enumeration value="ISA"/>
 *     &lt;enumeration value="ISM"/>
 *     &lt;enumeration value="IGC"/>
 *     &lt;enumeration value="RCA"/>
 *     &lt;enumeration value="TAS"/>
 *     &lt;enumeration value="NAS"/>
 *     &lt;enumeration value="IC"/>
 *     &lt;enumeration value="ND"/>
 *     &lt;enumeration value="IEA"/>
 *     &lt;enumeration value="NR"/>
 *     &lt;enumeration value="IBA"/>
 *     &lt;enumeration value="IBD"/>
 *     &lt;enumeration value="IKR"/>
 *     &lt;enumeration value="IRD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "evidenceType")
@XmlEnum
public enum EvidenceType {

    POTENTIAL,
    PROBABLE,
    BY_SIMILARITY,
    UNKNOWN,
    EXP,
    IDA,
    IPI,
    IMP,
    IGI,
    IEP,
    ISS,
    ISO,
    ISA,
    ISM,
    IGC,
    RCA,
    TAS,
    NAS,
    IC,
    ND,
    IEA,
    NR,
    IBA,
    IBD,
    IKR,
    IRD;

    public String value() {
        return name();
    }

    public static EvidenceType fromValue(String v) {
        return valueOf(v);
    }

}
