//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:17:16 PM CET 
//


package org.sphpp.nextprot.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dbName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="integrated" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="updated" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="lastSequenceUpdate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="sequenceVersion" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "historyEntry")
public class HistoryEntry {

    @XmlAttribute(name = "dbName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dbName;
    @XmlAttribute(name = "integrated", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar integrated;
    @XmlAttribute(name = "updated", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar updated;
    @XmlAttribute(name = "version")
    protected BigInteger version;
    @XmlAttribute(name = "lastSequenceUpdate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastSequenceUpdate;
    @XmlAttribute(name = "sequenceVersion")
    protected BigInteger sequenceVersion;

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbName(String value) {
        this.dbName = value;
    }

    /**
     * Gets the value of the integrated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIntegrated() {
        return integrated;
    }

    /**
     * Sets the value of the integrated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIntegrated(XMLGregorianCalendar value) {
        this.integrated = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the lastSequenceUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastSequenceUpdate() {
        return lastSequenceUpdate;
    }

    /**
     * Sets the value of the lastSequenceUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastSequenceUpdate(XMLGregorianCalendar value) {
        this.lastSequenceUpdate = value;
    }

    /**
     * Gets the value of the sequenceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceVersion() {
        return sequenceVersion;
    }

    /**
     * Sets the value of the sequenceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceVersion(BigInteger value) {
        this.sequenceVersion = value;
    }

}
