//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:17:16 PM CET 
//


package org.sphpp.nextprot.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}interactionXref"/>
 *         &lt;element ref="{}interactant" maxOccurs="unbounded"/>
 *         &lt;element ref="{}interactantXref" minOccurs="0"/>
 *         &lt;element ref="{}numberExperiments"/>
 *       &lt;/sequence>
 *       &lt;attribute name="qualityQualifier" use="required" type="{}qualityType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interactionXref",
    "interactant",
    "interactantXref",
    "numberExperiments"
})
@XmlRootElement(name = "interaction")
public class Interaction {

    @XmlElement(required = true)
    protected InteractionXref interactionXref;
    @XmlElement(required = true)
    protected List<Interactant> interactant;
    protected InteractantXref interactantXref;
    @XmlElement(required = true)
    protected BigInteger numberExperiments;
    @XmlAttribute(name = "qualityQualifier", required = true)
    protected QualityType qualityQualifier;

    /**
     * Gets the value of the interactionXref property.
     * 
     * @return
     *     possible object is
     *     {@link InteractionXref }
     *     
     */
    public InteractionXref getInteractionXref() {
        return interactionXref;
    }

    /**
     * Sets the value of the interactionXref property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteractionXref }
     *     
     */
    public void setInteractionXref(InteractionXref value) {
        this.interactionXref = value;
    }

    /**
     * Gets the value of the interactant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInteractant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Interactant }
     * 
     * 
     */
    public List<Interactant> getInteractant() {
        if (interactant == null) {
            interactant = new ArrayList<Interactant>();
        }
        return this.interactant;
    }

    /**
     * Gets the value of the interactantXref property.
     * 
     * @return
     *     possible object is
     *     {@link InteractantXref }
     *     
     */
    public InteractantXref getInteractantXref() {
        return interactantXref;
    }

    /**
     * Sets the value of the interactantXref property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteractantXref }
     *     
     */
    public void setInteractantXref(InteractantXref value) {
        this.interactantXref = value;
    }

    /**
     * Gets the value of the numberExperiments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberExperiments() {
        return numberExperiments;
    }

    /**
     * Sets the value of the numberExperiments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberExperiments(BigInteger value) {
        this.numberExperiments = value;
    }

    /**
     * Gets the value of the qualityQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link QualityType }
     *     
     */
    public QualityType getQualityQualifier() {
        return qualityQualifier;
    }

    /**
     * Sets the value of the qualityQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityType }
     *     
     */
    public void setQualityQualifier(QualityType value) {
        this.qualityQualifier = value;
    }

}
