//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:17:16 PM CET 
//


package org.sphpp.nextprot.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}transcript" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}exonsComposition" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isoMainName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uniqueName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transcript",
    "exonsComposition"
})
@XmlRootElement(name = "isoformMapping")
public class IsoformMapping {

    protected List<Transcript> transcript;
    protected ExonsComposition exonsComposition;
    @XmlAttribute(name = "isoMainName", required = true)
    protected String isoMainName;
    @XmlAttribute(name = "uniqueName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uniqueName;

    /**
     * Gets the value of the transcript property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transcript property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTranscript().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transcript }
     * 
     * 
     */
    public List<Transcript> getTranscript() {
        if (transcript == null) {
            transcript = new ArrayList<Transcript>();
        }
        return this.transcript;
    }

    /**
     * Gets the value of the exonsComposition property.
     * 
     * @return
     *     possible object is
     *     {@link ExonsComposition }
     *     
     */
    public ExonsComposition getExonsComposition() {
        return exonsComposition;
    }

    /**
     * Sets the value of the exonsComposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExonsComposition }
     *     
     */
    public void setExonsComposition(ExonsComposition value) {
        this.exonsComposition = value;
    }

    /**
     * Gets the value of the isoMainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsoMainName() {
        return isoMainName;
    }

    /**
     * Sets the value of the isoMainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsoMainName(String value) {
        this.isoMainName = value;
    }

    /**
     * Gets the value of the uniqueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * Sets the value of the uniqueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueName(String value) {
        this.uniqueName = value;
    }

}
