//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:17:16 PM CET 
//


package org.sphpp.nextprot.xml;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sphpp.nextprot package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Position_QNAME = new QName("", "position");
    private final static QName _NumberOfEntries_QNAME = new QName("", "numberOfEntries");
    private final static QName _NumberExperiments_QNAME = new QName("", "numberExperiments");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _DbName_QNAME = new QName("", "dbName");
    private final static QName _Sequence_QNAME = new QName("", "sequence");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _FamilyName_QNAME = new QName("", "familyName");
    private final static QName _ApplicationRelease_QNAME = new QName("", "applicationRelease");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _DatabaseRelease_QNAME = new QName("", "databaseRelease");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sphpp.nextprot
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Transcript }
     * 
     */
    public Transcript createTranscript() {
        return new Transcript();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link ProteinExistence }
     * 
     */
    public ProteinExistence createProteinExistence() {
        return new ProteinExistence();
    }

    /**
     * Create an instance of {@link Identifiers }
     * 
     */
    public Identifiers createIdentifiers() {
        return new Identifiers();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link ChromosomalLocations }
     * 
     */
    public ChromosomalLocations createChromosomalLocations() {
        return new ChromosomalLocations();
    }

    /**
     * Create an instance of {@link ChromosomalLocation }
     * 
     */
    public ChromosomalLocation createChromosomalLocation() {
        return new ChromosomalLocation();
    }

    /**
     * Create an instance of {@link ExperimentalEvidences }
     * 
     */
    public ExperimentalEvidences createExperimentalEvidences() {
        return new ExperimentalEvidences();
    }

    /**
     * Create an instance of {@link ExperimentalEvidence }
     * 
     */
    public ExperimentalEvidence createExperimentalEvidence() {
        return new ExperimentalEvidence();
    }

    /**
     * Create an instance of {@link AnnotationList }
     * 
     */
    public AnnotationList createAnnotationList() {
        return new AnnotationList();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link CvTerm }
     * 
     */
    public CvTerm createCvTerm() {
        return new CvTerm();
    }

    /**
     * Create an instance of {@link Variant }
     * 
     */
    public Variant createVariant() {
        return new Variant();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Evidences }
     * 
     */
    public Evidences createEvidences() {
        return new Evidences();
    }

    /**
     * Create an instance of {@link Evidence }
     * 
     */
    public Evidence createEvidence() {
        return new Evidence();
    }

    /**
     * Create an instance of {@link IsoformSpecificity }
     * 
     */
    public IsoformSpecificity createIsoformSpecificity() {
        return new IsoformSpecificity();
    }

    /**
     * Create an instance of {@link IsoformAnnot }
     * 
     */
    public IsoformAnnot createIsoformAnnot() {
        return new IsoformAnnot();
    }

    /**
     * Create an instance of {@link Positions }
     * 
     */
    public Positions createPositions() {
        return new Positions();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link Xrefs }
     * 
     */
    public Xrefs createXrefs() {
        return new Xrefs();
    }

    /**
     * Create an instance of {@link Xref }
     * 
     */
    public Xref createXref() {
        return new Xref();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     */
    public Authors createAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Consortium }
     * 
     */
    public Consortium createConsortium() {
        return new Consortium();
    }

    /**
     * Create an instance of {@link Interactant }
     * 
     */
    public Interactant createInteractant() {
        return new Interactant();
    }

    /**
     * Create an instance of {@link NeXtProt }
     * 
     */
    public NeXtProt createNeXtProt() {
        return new NeXtProt();
    }

    /**
     * Create an instance of {@link Family }
     * 
     */
    public Family createFamily() {
        return new Family();
    }

    /**
     * Create an instance of {@link Protein }
     * 
     */
    public Protein createProtein() {
        return new Protein();
    }

    /**
     * Create an instance of {@link ProteinNames }
     * 
     */
    public ProteinNames createProteinNames() {
        return new ProteinNames();
    }

    /**
     * Create an instance of {@link EntityName }
     * 
     */
    public EntityName createEntityName() {
        return new EntityName();
    }

    /**
     * Create an instance of {@link Synonyms }
     * 
     */
    public Synonyms createSynonyms() {
        return new Synonyms();
    }

    /**
     * Create an instance of {@link AdditionalNames }
     * 
     */
    public AdditionalNames createAdditionalNames() {
        return new AdditionalNames();
    }

    /**
     * Create an instance of {@link FunctionalRegionNames }
     * 
     */
    public FunctionalRegionNames createFunctionalRegionNames() {
        return new FunctionalRegionNames();
    }

    /**
     * Create an instance of {@link CleavedRegionNames }
     * 
     */
    public CleavedRegionNames createCleavedRegionNames() {
        return new CleavedRegionNames();
    }

    /**
     * Create an instance of {@link GeneNames }
     * 
     */
    public GeneNames createGeneNames() {
        return new GeneNames();
    }

    /**
     * Create an instance of {@link Families }
     * 
     */
    public Families createFamilies() {
        return new Families();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link HistoryEntry }
     * 
     */
    public HistoryEntry createHistoryEntry() {
        return new HistoryEntry();
    }

    /**
     * Create an instance of {@link Annotations }
     * 
     */
    public Annotations createAnnotations() {
        return new Annotations();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Interactions }
     * 
     */
    public Interactions createInteractions() {
        return new Interactions();
    }

    /**
     * Create an instance of {@link Interaction }
     * 
     */
    public Interaction createInteraction() {
        return new Interaction();
    }

    /**
     * Create an instance of {@link InteractionXref }
     * 
     */
    public InteractionXref createInteractionXref() {
        return new InteractionXref();
    }

    /**
     * Create an instance of {@link InteractantXref }
     * 
     */
    public InteractantXref createInteractantXref() {
        return new InteractantXref();
    }

    /**
     * Create an instance of {@link Isoforms }
     * 
     */
    public Isoforms createIsoforms() {
        return new Isoforms();
    }

    /**
     * Create an instance of {@link Isoform }
     * 
     */
    public Isoform createIsoform() {
        return new Isoform();
    }

    /**
     * Create an instance of {@link GenomicMapping }
     * 
     */
    public GenomicMapping createGenomicMapping() {
        return new GenomicMapping();
    }

    /**
     * Create an instance of {@link Gene }
     * 
     */
    public Gene createGene() {
        return new Gene();
    }

    /**
     * Create an instance of {@link IsoformMappings }
     * 
     */
    public IsoformMappings createIsoformMappings() {
        return new IsoformMappings();
    }

    /**
     * Create an instance of {@link IsoformMapping }
     * 
     */
    public IsoformMapping createIsoformMapping() {
        return new IsoformMapping();
    }

    /**
     * Create an instance of {@link ExonsComposition }
     * 
     */
    public ExonsComposition createExonsComposition() {
        return new ExonsComposition();
    }

    /**
     * Create an instance of {@link Exon }
     * 
     */
    public Exon createExon() {
        return new Exon();
    }

    /**
     * Create an instance of {@link PositionOnGene }
     * 
     */
    public PositionOnGene createPositionOnGene() {
        return new PositionOnGene();
    }

    /**
     * Create an instance of {@link AminoAcid }
     * 
     */
    public AminoAcid createAminoAcid() {
        return new AminoAcid();
    }

    /**
     * Create an instance of {@link Publications }
     * 
     */
    public Publications createPublications() {
        return new Publications();
    }

    /**
     * Create an instance of {@link Publication }
     * 
     */
    public Publication createPublication() {
        return new Publication();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link Pages }
     * 
     */
    public Pages createPages() {
        return new Pages();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Release }
     * 
     */
    public Release createRelease() {
        return new Release();
    }

    /**
     * Create an instance of {@link DataSources }
     * 
     */
    public DataSources createDataSources() {
        return new DataSources();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Proteins }
     * 
     */
    public Proteins createProteins() {
        return new Proteins();
    }

    /**
     * Create an instance of {@link NextprotExport }
     * 
     */
    public NextprotExport createNextprotExport() {
        return new NextprotExport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PositionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "position")
    public JAXBElement<PositionType> createPosition(PositionType value) {
        return new JAXBElement<PositionType>(_Position_QNAME, PositionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfEntries")
    public JAXBElement<BigInteger> createNumberOfEntries(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfEntries_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberExperiments")
    public JAXBElement<BigInteger> createNumberExperiments(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberExperiments_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dbName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createDbName(String value) {
        return new JAXBElement<String>(_DbName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sequence")
    public JAXBElement<String> createSequence(String value) {
        return new JAXBElement<String>(_Sequence_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "familyName")
    public JAXBElement<String> createFamilyName(String value) {
        return new JAXBElement<String>(_FamilyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationRelease")
    public JAXBElement<String> createApplicationRelease(String value) {
        return new JAXBElement<String>(_ApplicationRelease_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "databaseRelease")
    public JAXBElement<XMLGregorianCalendar> createDatabaseRelease(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatabaseRelease_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
