//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:17:16 PM CET 
//


package org.sphpp.nextprot.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for positionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="positionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="first" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="firstStatus" type="{}positionStatusType" default="certain" />
 *       &lt;attribute name="last" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="lastStatus" type="{}positionStatusType" default="certain" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "positionType")
public class PositionType {

    @XmlAttribute(name = "first")
    protected BigInteger first;
    @XmlAttribute(name = "firstStatus")
    protected PositionStatusType firstStatus;
    @XmlAttribute(name = "last")
    protected BigInteger last;
    @XmlAttribute(name = "lastStatus")
    protected PositionStatusType lastStatus;

    /**
     * Gets the value of the first property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFirst() {
        return first;
    }

    /**
     * Sets the value of the first property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFirst(BigInteger value) {
        this.first = value;
    }

    /**
     * Gets the value of the firstStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PositionStatusType }
     *     
     */
    public PositionStatusType getFirstStatus() {
        if (firstStatus == null) {
            return PositionStatusType.CERTAIN;
        } else {
            return firstStatus;
        }
    }

    /**
     * Sets the value of the firstStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionStatusType }
     *     
     */
    public void setFirstStatus(PositionStatusType value) {
        this.firstStatus = value;
    }

    /**
     * Gets the value of the last property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLast() {
        return last;
    }

    /**
     * Sets the value of the last property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLast(BigInteger value) {
        this.last = value;
    }

    /**
     * Gets the value of the lastStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PositionStatusType }
     *     
     */
    public PositionStatusType getLastStatus() {
        if (lastStatus == null) {
            return PositionStatusType.CERTAIN;
        } else {
            return lastStatus;
        }
    }

    /**
     * Sets the value of the lastStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionStatusType }
     *     
     */
    public void setLastStatus(PositionStatusType value) {
        this.lastStatus = value;
    }

}
