//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:17:16 PM CET 
//


package org.sphpp.nextprot.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}proteinExistence"/>
 *         &lt;element ref="{}proteinNames"/>
 *         &lt;element ref="{}additionalNames" minOccurs="0"/>
 *         &lt;element ref="{}functionalRegionNames" minOccurs="0"/>
 *         &lt;element ref="{}cleavedRegionNames" minOccurs="0"/>
 *         &lt;element ref="{}geneNames" minOccurs="0"/>
 *         &lt;element ref="{}families" minOccurs="0"/>
 *         &lt;element ref="{}history"/>
 *         &lt;element ref="{}annotations"/>
 *         &lt;element ref="{}keywords"/>
 *         &lt;element ref="{}interactions" minOccurs="0"/>
 *         &lt;element ref="{}isoforms"/>
 *         &lt;element ref="{}chromosomalLocations" minOccurs="0"/>
 *         &lt;element ref="{}genomicMapping" minOccurs="0"/>
 *         &lt;element ref="{}identifiers" minOccurs="0"/>
 *         &lt;element ref="{}publications" minOccurs="0"/>
 *         &lt;element ref="{}xrefs"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uniqueName" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proteinExistence",
    "proteinNames",
    "additionalNames",
    "functionalRegionNames",
    "cleavedRegionNames",
    "geneNames",
    "families",
    "history",
    "annotations",
    "keywords",
    "interactions",
    "isoforms",
    "chromosomalLocations",
    "genomicMapping",
    "identifiers",
    "publications",
    "xrefs"
})
@XmlRootElement(name = "protein")
public class Protein {

    @XmlElement(required = true)
    protected ProteinExistence proteinExistence;
    @XmlElement(required = true)
    protected ProteinNames proteinNames;
    protected AdditionalNames additionalNames;
    protected FunctionalRegionNames functionalRegionNames;
    protected CleavedRegionNames cleavedRegionNames;
    protected GeneNames geneNames;
    protected Families families;
    @XmlElement(required = true)
    protected History history;
    @XmlElement(required = true)
    protected Annotations annotations;
    @XmlElement(required = true)
    protected Keywords keywords;
    protected Interactions interactions;
    @XmlElement(required = true)
    protected Isoforms isoforms;
    protected ChromosomalLocations chromosomalLocations;
    protected GenomicMapping genomicMapping;
    protected Identifiers identifiers;
    protected Publications publications;
    @XmlElement(required = true)
    protected Xrefs xrefs;
    @XmlAttribute(name = "uniqueName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String uniqueName;

    /**
     * Gets the value of the proteinExistence property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinExistence }
     *     
     */
    public ProteinExistence getProteinExistence() {
        return proteinExistence;
    }

    /**
     * Sets the value of the proteinExistence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinExistence }
     *     
     */
    public void setProteinExistence(ProteinExistence value) {
        this.proteinExistence = value;
    }

    /**
     * Gets the value of the proteinNames property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinNames }
     *     
     */
    public ProteinNames getProteinNames() {
        return proteinNames;
    }

    /**
     * Sets the value of the proteinNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinNames }
     *     
     */
    public void setProteinNames(ProteinNames value) {
        this.proteinNames = value;
    }

    /**
     * Gets the value of the additionalNames property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalNames }
     *     
     */
    public AdditionalNames getAdditionalNames() {
        return additionalNames;
    }

    /**
     * Sets the value of the additionalNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalNames }
     *     
     */
    public void setAdditionalNames(AdditionalNames value) {
        this.additionalNames = value;
    }

    /**
     * Gets the value of the functionalRegionNames property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionalRegionNames }
     *     
     */
    public FunctionalRegionNames getFunctionalRegionNames() {
        return functionalRegionNames;
    }

    /**
     * Sets the value of the functionalRegionNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionalRegionNames }
     *     
     */
    public void setFunctionalRegionNames(FunctionalRegionNames value) {
        this.functionalRegionNames = value;
    }

    /**
     * Gets the value of the cleavedRegionNames property.
     * 
     * @return
     *     possible object is
     *     {@link CleavedRegionNames }
     *     
     */
    public CleavedRegionNames getCleavedRegionNames() {
        return cleavedRegionNames;
    }

    /**
     * Sets the value of the cleavedRegionNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link CleavedRegionNames }
     *     
     */
    public void setCleavedRegionNames(CleavedRegionNames value) {
        this.cleavedRegionNames = value;
    }

    /**
     * Gets the value of the geneNames property.
     * 
     * @return
     *     possible object is
     *     {@link GeneNames }
     *     
     */
    public GeneNames getGeneNames() {
        return geneNames;
    }

    /**
     * Sets the value of the geneNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneNames }
     *     
     */
    public void setGeneNames(GeneNames value) {
        this.geneNames = value;
    }

    /**
     * Gets the value of the families property.
     * 
     * @return
     *     possible object is
     *     {@link Families }
     *     
     */
    public Families getFamilies() {
        return families;
    }

    /**
     * Sets the value of the families property.
     * 
     * @param value
     *     allowed object is
     *     {@link Families }
     *     
     */
    public void setFamilies(Families value) {
        this.families = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
    public History getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
    public void setHistory(History value) {
        this.history = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link Annotations }
     *     
     */
    public Annotations getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotations }
     *     
     */
    public void setAnnotations(Annotations value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link Keywords }
     *     
     */
    public Keywords getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keywords }
     *     
     */
    public void setKeywords(Keywords value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the interactions property.
     * 
     * @return
     *     possible object is
     *     {@link Interactions }
     *     
     */
    public Interactions getInteractions() {
        return interactions;
    }

    /**
     * Sets the value of the interactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interactions }
     *     
     */
    public void setInteractions(Interactions value) {
        this.interactions = value;
    }

    /**
     * Gets the value of the isoforms property.
     * 
     * @return
     *     possible object is
     *     {@link Isoforms }
     *     
     */
    public Isoforms getIsoforms() {
        return isoforms;
    }

    /**
     * Sets the value of the isoforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Isoforms }
     *     
     */
    public void setIsoforms(Isoforms value) {
        this.isoforms = value;
    }

    /**
     * Gets the value of the chromosomalLocations property.
     * 
     * @return
     *     possible object is
     *     {@link ChromosomalLocations }
     *     
     */
    public ChromosomalLocations getChromosomalLocations() {
        return chromosomalLocations;
    }

    /**
     * Sets the value of the chromosomalLocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChromosomalLocations }
     *     
     */
    public void setChromosomalLocations(ChromosomalLocations value) {
        this.chromosomalLocations = value;
    }

    /**
     * Gets the value of the genomicMapping property.
     * 
     * @return
     *     possible object is
     *     {@link GenomicMapping }
     *     
     */
    public GenomicMapping getGenomicMapping() {
        return genomicMapping;
    }

    /**
     * Sets the value of the genomicMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenomicMapping }
     *     
     */
    public void setGenomicMapping(GenomicMapping value) {
        this.genomicMapping = value;
    }

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Identifiers }
     *     
     */
    public Identifiers getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifiers }
     *     
     */
    public void setIdentifiers(Identifiers value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the publications property.
     * 
     * @return
     *     possible object is
     *     {@link Publications }
     *     
     */
    public Publications getPublications() {
        return publications;
    }

    /**
     * Sets the value of the publications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publications }
     *     
     */
    public void setPublications(Publications value) {
        this.publications = value;
    }

    /**
     * Gets the value of the xrefs property.
     * 
     * @return
     *     possible object is
     *     {@link Xrefs }
     *     
     */
    public Xrefs getXrefs() {
        return xrefs;
    }

    /**
     * Sets the value of the xrefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xrefs }
     *     
     */
    public void setXrefs(Xrefs value) {
        this.xrefs = value;
    }

    /**
     * Gets the value of the uniqueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * Sets the value of the uniqueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueName(String value) {
        this.uniqueName = value;
    }

}
